import { ReactNode } from "react"
import "@styles/globals.css"
import 'leaflet/dist/leaflet.css';
import ReduxProvider from "@components/ReduxProvider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props{
  children?: ReactNode
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>

        <ReduxProvider>
          {children}
        </ReduxProvider>

      </body>
    </html>
  )
}

export default RootLayout;