import { ReactNode } from "react"
import "@styles/globals.css"
import 'leaflet/dist/leaflet.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props{
  children?: ReactNode
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}

export default RootLayout;